version: "3.8"

services:
  prm392-server-container:
    container_name: prm392-server-container
    build:
      context: .
      dockerfile: DockerfileDotNet
    ports:
      - "7267:7267"
    networks:
      - prm392-network
    env_file:
      - PRM392.API/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7267"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
networks:
  prm392-network:
    name: prm392-network
    driver: bridge

